### ISSUE TITLE
[Example] can not run example app

### ISSUE THREAD

**Issue by aviadhahami** [jacklam718/react-native-popup-dialog#1]
Hey @jacklam718 :)
Good work!
I'm having troubles running the example app.
First thing I've noticed in the `package.json` is that you're requiring the file from your (very) own personal pc, thus I've got errors all over...
Will try to solve it and PR

**Comment by jacklam718** [comment]
@aviadhahami Haha ~~ 
Sorry about that.
Will welcome your PR 👍

**Comment by aviadhahami** [comment]
:)
I'm also removing the fancy button is it won't link properly and won't compile

**Comment by jacklam718** [comment]
Link should work properly, what error you get? Can you show me the error messages

**Comment by aviadhahami** [comment]
Can't really as it fills my whole screen.
Bottom line - the linear-gradient package won't link

**Comment by jacklam718** [comment]
Can you try to Link the ART library? You'll find ReactART library in node_modules/react-native/Libraries/ART/ART.xcodeproj

Detailed https://facebook.github.io/react-native/docs/linking-libraries-ios.html#content

**Comment by jacklam718** [comment]
What OS you use? IOS or Android?

**Comment by jacklam718** [comment]
Ok, just remove it if still breaking.

**Comment by aviadhahami** [comment]
i know :+1: 
Will PR that in couple of minutes
