### ISSUE TITLE
Dismiss function

### ISSUE THREAD

**Issue by KoenvGinkel** [jacklam718/react-native-popup-dialog#100]
The dismiss function doesn't work.
But the .show function does. anyone who can solve this?

**Comment by jacklam718** [comment]
@KoenvGinkel You solved?

**Comment by KoenvGinkel** [comment]
I did. had to use .bind(this) in the function

**Comment by KoenvGinkel** [comment]
`onPress={this.submitURI.bind(this)}`

together with:

` submitURI(){
    this.fadeAnimationDialog.dismiss();
  }
`
