### ISSUE TITLE
this.popupDialog returns undefined when component is rendered

### ISSUE THREAD

**Issue by xMaarf** [jacklam718/react-native-popup-dialog#103]
I'm trying to open the popup when my component is mounted but it returns undefined.
The only way that I got it working is by passing a setTimeout method and then call my function that I'm using to show the popup. But I don't like the way that I'm executing this.
I was thinking if it's possible to have a prop that listens when ever the popupDialog is ready, something like this: 
```
<PopupDialog onReady={this.myFunction} >
(...)
</PopupDialog>
```
or if there's a more practical way to achieve this instead of using a setTimeout method.
Hope this makes sense. 
Thanks.

**Comment by jacklam718** [comment]
@xMaarf 
you can try this
```javascript
class App extends Component {
  state = {
    dialogShow: false
  }
  
  componentWillMount() {
    this.setState({ dialogShow: true })
  }

  render() {
    <PopupDialog show={this.state.dialogShow}>
      {...}
    </PopupDialog>
  }
}
```
