### ISSUE TITLE
Add dismiss "x" button top right

### ISSUE THREAD

**Issue by m-deacon** [jacklam718/react-native-popup-dialog#105]
Hi @jacklam718 

Firstly, thank you for creating this component. It works really well!

I was wondering if it were to be possible to add a prop called something like "dismissIcon" that would show/hide an "x" button on the top right of the pop up that when pressed calls the "popupDialog.dismiss()" method?

I would think the easiest implementation would be to link it to using DialogTitle so that it's part of the DialogTitle component or perhaps it could sit slightly above the dialog box.

**Comment by jacklam718** [comment]
Hey Hi @m-deacon FYI https://github.com/jacklam718/react-native-popup-dialog/issues/14

**Comment by m-deacon** [comment]
Oh my. I did search for that - couldn't find it. Thanks for the link!
