### ISSUE TITLE
ScaleAnimation with param causes the error 

### ISSUE THREAD

**Issue by heyman333** [jacklam718/react-native-popup-dialog#106]
First of all, my development environment as like below
`"react": "16.2.0",  "react-native": "0.53.3"`

I tried to create ScaleAnimation with `toValue` prameter as you described in document 
`const scaleAnimation = new ScaleAnimation({ toValue: 10 })`
but, it never works with below error message

> Invariant Violation: Cannot interpolate an input which is not a number

am I missing something?

**Comment by jacklam718** [comment]
not accept object argument.
Usage:
`new ScaleAnimation(10)`
