### ISSUE TITLE
onDismissed call when opening popup

### ISSUE THREAD

**Issue by ZeroCool00** [jacklam718/react-native-popup-dialog#108]
Why this method call when we open dialog, it should be call when we close dialog. 

```
<PopupDialog
        ref={(popupDialog) => { this.popupDialogInvite = popupDialog; }}
         dismissOnHardwareBackPress
         onDismissed={() => console.log('dismiss call')}
         width={400}
         height={170
   >
```

**Comment by jacklam718** [comment]
@ZeroCool00 I can't reproduce the issue.

As you can see in the following, `onDismissed` method only be called when dialog dismissed.
![dialog](https://user-images.githubusercontent.com/5494638/40463710-48550f16-5f49-11e8-8f6c-03e428cb32b2.gif)
