### ISSUE TITLE
How to change contentView backgroundColor

### ISSUE THREAD

**Issue by bawn** [jacklam718/react-native-popup-dialog#11]
I want to change contentView background color, but not cover a new view set background color

follow code not work
```
<PopupDialog
            style={{backgroundColor: 'transparent'}}
            ref={(popupDialog) => { this.popupDialog = popupDialog;}}
            width={Dimensions.get('window').width}
            height={Dimensions.get('window').height}
            haveTitleBar={false}
            dialogAnimation = { new SlideAnimation({ slideFrom: 'bottom' }) }
            onClosed={()=>{Actions.pop()}}
            >
              {this._popupView()}
            </PopupDialog>
```
The contentView still white background color

**Comment by jacklam718** [comment]
@bawn 
You can pass a `<View />` as the `contentView` that's mean you can set any content & any style  on the `<View />`. For example:


```javascript
<PopupDialog
  ref={(popupDialog) => { this.popupDialog = popupDialog; }}
>
  <View
    style={{
      backgroundColor: 'red',
    }}
  >
    <Text>Hello</Text>
  </View>
</PopupDialog>
```

**Comment by bawn** [comment]
@jacklam718 Thanks, I mean i just to want change PopupDialog background color,  but not cover a new view set background color

**Comment by jacklam718** [comment]
@bawn 
I see, I understand what you mean is.
You want to pass style to change the popupDialog style, is it right?

**Comment by bawn** [comment]
@jacklam718 YES

**Comment by jacklam718** [comment]
@bawn 
Sorry it's not yet support 😔 I will make it support. 

I will let you know when I updated.
Thanks for reporting this issue.

**Comment by jacklam718** [comment]
@bawn 
Updated.
Please install the latest: 0.2.13 if any problems please let me know.

**Comment by bawn** [comment]
@jacklam718 Thanks

**Comment by bawn** [comment]
@jacklam718 


Still can not change the background color

```
<PopupDialog
            style={{backgroundColor: 'red'}}
            ref={(popupDialog) => { this.popupDialog = popupDialog;}}
            width={Dimensions.get('window').width}
            height={Dimensions.get('window').height}
            haveTitleBar={false}
            dialogAnimation = { new SlideAnimation({ slideFrom: 'bottom' }) }
            onClosed={()=>{Actions.pop()}}
            >

            </PopupDialog>
```

![simulator screen shot 29 oct 2016 9 03 07 pm](https://cloud.githubusercontent.com/assets/7238866/19829693/2c590088-9e1b-11e6-8ae4-b289849db09f.png)

**Comment by jacklam718** [comment]
@bawn the prop is `dialogStyle` rather than  `style`

**Comment by bawn** [comment]
@jacklam718 Thanks, It's worked
