### ISSUE TITLE
PopupDialog subview does not display after setting dialogAnimation, only overlay is displayed

### ISSUE THREAD

**Issue by TrustTheBoy** [jacklam718/react-native-popup-dialog#114]
@jacklam718  Can only be assigned once to the animation, using the judgment statement for a second reassignment, the content is not displayed
## Case presentation:(A total of three png)
![image](https://user-images.githubusercontent.com/20201085/41446762-0dccdfda-7084-11e8-8241-5db8723801aa.png)

![71529030497_ pic_hd](https://user-images.githubusercontent.com/20201085/41447639-bff5ed88-7088-11e8-8e9f-741c4a6e84a1.jpg)

![81529030516_ pic_hd](https://user-images.githubusercontent.com/20201085/41447644-c19da202-7088-11e8-87c1-cacee0cc71c3.jpg)

But when I click Toggle Inspector > click Touchables, this popup appears:(1个GIF:size = 6.2M)

![qq20180615-110338-hd](https://user-images.githubusercontent.com/20201085/41448248-1621a3f2-708c-11e8-8121-a3cea3cb7d7d.gif)

**Comment by jacklam718** [comment]
it seems you using this library wrongly. I would you recommend you follow my example.
