### ISSUE TITLE
callback of dismiss function is called before closing of dialog

### ISSUE THREAD

**Issue by punksta** [jacklam718/react-native-popup-dialog#115]
`dismiss` accepts callback function but it's called before closing of dialog. I think we should wait of animation end here:
https://github.com/jacklam718/react-native-popup-dialog/blob/13f9df2c1dce23962add8a08ef10647e4971b8ed/src/components/Dialog.js#L150-L15

**Comment by jacklam718** [comment]
@punksta you can use `dismissed` prop.

**Comment by jacklam718** [comment]
for example:
```
<PopupDialog
  onDismissed={() => {
  }}
>
</PopupDialog>
```

**Comment by punksta** [comment]
thanks! works as expected.
