### ISSUE TITLE
Update show to false, PopupDialog will flash

### ISSUE THREAD

**Issue by TrustTheBoy** [jacklam718/react-native-popup-dialog#116]
When the property `show` is used to control PopupDialog  display and hide operations, updating the value of show to false will restore the initial size, and will quickly flash at will.
The following is a demo Gif：
![jun-29-2018 10-07-27](https://user-images.githubusercontent.com/20201085/42069571-243e7b1e-7b85-11e8-9609-9612b6445c94.gif)

Using `this.popupdialog.dismiss()` does not happen

**Comment by TrustTheBoy** [comment]
@jacklam718 Sorry, I ran your example again and tried to reproduce my problem. However, the case was normal and there was no abnormality. It may be my own problem. Thank you.

**Comment by jacklam718** [comment]
no worries man.
