### ISSUE TITLE
Opacity setting question

### ISSUE THREAD

**Issue by XeCtvi** [jacklam718/react-native-popup-dialog#117]
Hi all and @jacklam718 ,

I want something like:
![demo](https://user-images.githubusercontent.com/10743176/42216441-607a76c4-7ef4-11e8-805a-2a721f2189f6.png)

But the dialog opacity will override the title one. The title will have opacity set as 0.3 though I set it to 1.

How to achieve that, Any suggestion?

```
<PopupDialog dialogTitle={<DialogTitle title="库房管理" haveTitleBar={false} titleTextStyle={{opacity: 1, color: "white", fontSize: 30 }} />}
             width={0.5}
             dialogAnimation={scaleAnimation}
             overlayBackgroundColor="#000"
             dialogStyle={{backgroundColor: "#000", opacity: 0.3}}
             ref={(popupDialog) => {
                 this.popupDialog = popupDialog;
             }}>
    <View>
        <Text style={{color: "white", opacity: 1}}>Hello!</Text>
    </View>
</PopupDialog>
```
![demo2](https://user-images.githubusercontent.com/10743176/42217068-671923de-7ef6-11e8-853c-b972749bd4a8.png)

Thanks.

**Comment by XeCtvi** [comment]
Hi all,

> When using the opacity property you are changing the entire opacity of the view you are applying the property on. Any child components will inherit this opacity. In this case opacity should be applied on the color only.

I will close this question for now. 

Thanks.

**Comment by jacklam718** [comment]
You resolved?

**Comment by AKclown** [comment]
backgroundColor: 'rgba(255,255,255,.8)',
