### ISSUE TITLE
Unable to resolve module 'react-native'  from ReactNativePropRegistry

### ISSUE THREAD

**Issue by sananddev** [jacklam718/react-native-popup-dialog#119]
![screenshot_1530784236](https://user-images.githubusercontent.com/35886764/42316517-c3b51390-8069-11e8-8e97-1a6fb57931d5.png)
import React, { Component } from 'react';
import {View,StyleSheet,Image,Alert ,TouchableOpacity} from 'react-native';
import { Container, Header,Right, Title, Content,   Footer, FooterTab, Button,
   Left, Body, Icon, Text } from 'native-base';
export default class AnatomyExample extends Component {

  render() {
    return (
      <Container>
        <Header>
          <Left>
            <Button transparent>
              <Icon name='menu' />
            </Button>
          </Left>
          <Body>
            <Title></Title>
          </Body>
          <Right>
            <Icon name="search"></Icon>
          </Right>
         </Header>
        <Content>
     <View>
       /* start of a view for image */
       <View style={styles.firstpane}>
         <TouchableOpacity onPress={this.popupDialog,show()}>
           <Image style={{flex:35}} source={require('./5.jpg')}/>
         </TouchableOpacity>
         <PopupDialog
      ref={(popupDialog) => { this.popupDialog = popupDialog; }}
    >
      <View>
        <Text>Hello</Text>
      </View>
    </PopupDialog>
       </View>
     </View>
        </Content>
        <Footer>
          <FooterTab>
                     <Button>
                       <Icon name="apps" />
                     </Button>
                     <Button>
                       <Icon name="camera" />
                     </Button>
                     <Button active>
                       <Icon active name="navigate" />
                     </Button>

                     <Button >
                       <Icon  name="location" />
                     </Button>
                     <Button>
                       <Icon name="person" />
                     </Button>
                   </FooterTab>
        </Footer>
      </Container>
    );
  }
}

// stylesheets are left intentionally blank for nothing
const styles=StyleSheet.create({
  firstpane:{

  },
  underpane:{

  },
  forgroundpane:{

  }
})

**Comment by jacklam718** [comment]
from the error message seems not related to this library.....
