### ISSUE TITLE
How to Access ref to other component?

### ISSUE THREAD

**Issue by Albert0405** [jacklam718/react-native-popup-dialog#120]
I wanted to show the dialog when i press a button but the button is in another component/file

//Dialog.js
```
<PopupDialog
          ref={e => {
            this.popupDialog = e;
          }}
          dialogAnimation={slideAnimation}
          dialogStyle={styles.modalContainer}
          width={0.87}
          height={0.58}
   />
```

//OtherComponent.js
```
<Button onPress={() => { 
       this.popupDialog.show();
    }} 
/>
```

**Comment by XeCtvi** [comment]
@Albert0405 Hi there, Have you figure it out? I just want to know how to resolve it too :)

**Comment by Albert0405** [comment]
@XeCtvi  Sorry i dont use this plugin anymore, i use `react-native-simple-dialogs` instead

**Comment by jacklam718** [comment]
sounds like not related to this library.
