### ISSUE TITLE
Integrate with reactnavigation has issue

### ISSUE THREAD

**Issue by XeCtvi** [jacklam718/react-native-popup-dialog#122]
Hi there,

While I am using our `react-native-popup-dialog` in react-navigation's header button to trigger the show method. Something strange happens.

All my popup dialogs cannot close correctly and keep alive though in others page.

    static navigationOptions = ({ navigation }) => {
        return {
            headerRight: (
                <HeaderButtons HeaderButtonComponent={headerButton}>
                    <Item title="search" iconName="search" buttonStyle={{ color: "white" }} onPress={navigation.getParam("popUpDialog") }/>
                </HeaderButtons>
            )
        };
    };

    componentDidMount() {
        this.props.navigation.setParams({ popUpDialog: this._searchPopUpDialog });
    }

    _searchPopUpDialog = () => {
        this.popupSearchDialog.show();
    };

Any solution?

**Comment by XeCtvi** [comment]
It should be closed when I am clicking the overlay or clicking elsewhere but it isn't. And the dialog occupied my whole component after I calling the show method. Seems like the ref issue?

I don't really know, it looks strange.

**Comment by XeCtvi** [comment]
Hi @jacklam718 ,

I haven't resolved this strange issue but I have integrated the dialog with the header button in the other way.

![Solution like](https://reactnavigation.org/docs/en/header-buttons.html)

I am using "state" to control the dialog's show and hide instead. Not directly calling the `show` method.

Thanks.

**Comment by jacklam718** [comment]
nice to hear that
