### ISSUE TITLE
Dialog is covered by other components.

### ISSUE THREAD

**Issue by a1onexiang2** [jacklam718/react-native-popup-dialog#125]
If the style of a component is set to
```javascript
{
    elevation: 1, // any number larger than 0,
    position: 'absolute', // or relative
}
```
When the dialog shows, the relative/absolute component on the same page with a elevation will show upon the dialog.
I tried to set a larger elevation, such as 1000, in dialogStyle, containerStyle, and in the style of dialog root content view but nothing happened.

I tried to change the source code. And it is fixed after I did the following changes in `Dialog.js`:
```javascript
container: {
    flex: 1,
    position: 'absolute',
    top: 0,
    left: 0,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
    elevation: 1000, // that's the point
  },
``` 

Everything seems to be alright on Android, but I have not tested it on iOS.
Hope it will be fixed and a new version will be released soon.
Thanks.

**Comment by jacklam718** [comment]
Did you try pass the following style into Dialog component via `containerStyle` prop?  
``` 
container: {
    flex: 1,
    position: 'absolute',
    top: 0,
    left: 0,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
    elevation: 1000, // that's the point
  }

some references might useful to you
https://github.com/jacklam718/react-native-popup-dialog/issues/88#issuecomment-381481420
https://github.com/jacklam718/react-native-popup-dialog/issues/88#issuecomment-394994744
