### ISSUE TITLE
Remove default dialog box?

### ISSUE THREAD

**Issue by mozamonkey** [jacklam718/react-native-popup-dialog#126]
How do I remove the default dialog box? I have added a View to the PopupDialog but there is a default view that appears underneath the view i've built:

```
 <PopupDialog
          ref={(fadeAnimationDialog) => {
            this.fadeAnimationDialog = fadeAnimationDialog;
          }}
        >
          <View style={styles.dialogContentView}>
                     CUSTOM CODE HERE
	</View>
		
 </PopupDialog>
```

**Comment by jacklam718** [comment]
you can't do that, but you can easily compose a new dialog with the following components.
```
Dialog
PopupDialog
DialogButton
DialogTitle
Overlay
Animation
FadeAnimation
ScaleAnimation
SlideAnimation
PopupDialogType
DialogType
DialogButtonType
DialogTitleType
OverlayType
```

**Comment by mozamonkey** [comment]
What would the code look like? I'm confused - i've added a view with custom code into the dialog box. Why is that not enough?
