### ISSUE TITLE
Not able to dismiss or show the modal using 'show' props 

### ISSUE THREAD

**Issue by faisalpathan** [jacklam718/react-native-popup-dialog#128]
I am trying to show / hide the dialog dependent upon the 'show' prop of popup-dialog , by updating state onPress of a button . But it does not work the state gets updated but the modal does not hide or show

**Comment by jacklam718** [comment]
could you show me your code?

**Comment by faisalpathan** [comment]
`state = {
    isVisible: false,
  };
   <View style={{ flex: 1, zIndex: 1 }}>
        <Button title="Show Dialog" onPress={() => this.setState({ isVisible: true })} />
        <PopupDialog
          ref={popupDialog => {
            this.popupDialog = popupDialog;
          }}
          dialogAnimation={slideAnimation}
          dismissOnTouchOutside={false}
          dialogStyle={{
            justifyContent: 'center',
            alignItems: 'center',
            zIndex: 1000,
            elevation: 1000, 
          }}
          containerStyle={{ zIndex: 1000, elevation: 1000 }}
          show={this.state.isVisible}
        >
          <View>
            <ActivityIndicator animating size="large" />
          </View>
        </PopupDialog>
      </View>`

**Comment by jacklam718** [comment]
you have change `isVisible` to `false` after you close dialog.
