### ISSUE TITLE
If multiple PopupDialog on my page ， How do you set different buttons to open different PopupDialog ?

### ISSUE THREAD

**Issue by wf357wf** [jacklam718/react-native-popup-dialog#130]
If multiple PopupDialog on my page ， How do you set different buttons to open different PopupDialog ?

**Comment by jacklam718** [comment]
you can take a look at my example. https://github.com/jacklam718/react-native-popup-dialog/blob/master/popup-dialog-example/App.js

**Comment by wf357wf** [comment]
Oh! I see.  Thank you
