### ISSUE TITLE
Support percentage specs for width/height

### ISSUE THREAD

**Issue by alpha0010** [jacklam718/react-native-popup-dialog#132]
Although the closing of #86 recommends using fractional values, that option does not work when the device is rotated.  Unless a re-render is forced, the old width/height will continue to be used, potentially forcing the edges off screen when switching landscape to portrait.

**Comment by alpha0010** [comment]
For now, overridden via: `dialogStyle={{width: "90%}}`.  Still think this would be a nice item to fix.  You could potentially just translate fractional values into percentages instead of computing absolute dimensions.

**Comment by jacklam718** [comment]
### percentage
```jsx
<Dialog 
  width={0.9} // 90%
/>
```
