### ISSUE TITLE
Major breaking change since 0.16.1

### ISSUE THREAD

**Issue by danielgindi** [jacklam718/react-native-popup-dialog#133]
Hi!

1. Dismissing from background overlay not working anymore
2. Dialog automatically stretches to full height of parent
3. Not showing at all automatically, only after playing with state a few times

Am I missing something?

Thank you :-)

**Comment by jacklam718** [comment]
1. you have to pass a `onTouchOutside` handler for handling the touch event. for example: https://github.com/jacklam718/react-native-popup-dialog/blob/master/popup-dialog-example/App.js#L145-L147
2. By default Dialog will auto size to the width, height of its children.
3. what do you mean by automatically?

**Comment by danielgindi** [comment]
1. Okay :-)
2. This does not happen, it only happens if I revert to 0.15.1, where autosizing works properly
3. Means that starting up with `visible: true` does not show the dialog. It has to start with `false`, and set to `true` later.

**Comment by jacklam718** [comment]
For point 2, I can't reproduce it sorry about that. For point 3, I've fixed it in `v0.16.2`
Thanks for reporting the issue :)

**Comment by danielgindi** [comment]
I found issue number 2: It's the removed defaults for
```
            width: Dimensions.get('window').width,
            height: 300,
```

**Comment by jacklam718** [comment]
yeah, but it should same height as child.

```javascript
<Dialog visible={this.state.defaultAnimationDialog}>
  <View>
    <Text>
      Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum is simply dummy text of the printing and typesetting industry. 
    </Text>
  </View>
</Dialog>
```

<img src="https://user-images.githubusercontent.com/5494638/49992285-8da3ee00-ffbe-11e8-8e8d-c33a4de92361.jpg" width="300" />

**Comment by danielgindi** [comment]
So for me it broke some code, as child as flex size, shrinkable/growable. I had to add the original style for the container for it to work properly.
Anyway you could decide now that you don't want to change that again, as I guess it will break stuff for other people, so you can close the issue. (Maybe add a note about this in the README?)

**Comment by jacklam718** [comment]
Yeah, I might add a note in the README.
Thanks @danielgindi
