### ISSUE TITLE
A close button on title bar

### ISSUE THREAD

**Issue by sances15** [jacklam718/react-native-popup-dialog#14]
@jacklam718 Is it possible to add a close button 'x' on the title bar?

**Comment by jacklam718** [comment]
@sances15 
Currently we cannot do that and I'm not planing to add `x` on title bar, because it is a very specific feature.
So I am thinking to make the component support custom title bar.
May be I will add a prop called `titlebar` let ppl can pass a  `View`  into the component via the `titlebar` prop.

**Comment by sances15** [comment]
@jacklam718 It's just that on a phone the overlay are is quite less, so the users have to fiddle on the sides to close the popup view. Passing a view would be awesome, that will help in customizing it any way we want.

**Comment by jacklam718** [comment]
@sances15 

It's support custom dialog title now. Please install v0.3.14
Example:
```
import { PopupDialog, DialogTitle } from 'react-native-popup-dialog';
 
<PopupDialog
  dialogTitle={<DialogTitle title="Dialog Title" />}
>
</PopupDialog>
```

If any problems please let me know, thanks.

**Comment by sances15** [comment]
@jacklam718 I was able to it get this working using dialogTitle={<View />}. I added a TouchableOpacity for the close button with an image in it. But how would i close this PopupDialog.
<TouchableOpacity style={styles.closeButton} onPress={this.popupDialog.closeDialog()}> This did not work.

**Comment by jacklam718** [comment]
@sances15 

here's have two examples I think it should works

```
# Example - 1
export default class PopupDialogExample extends Component {
  constructor(props) {
    super(props);

    this.state = {
      dialogOpen: false,
    };

    this.openDialog = this.openDialog.bind(this);
    this.closeDialog = this.closeDialog.bind(this);
  }

  openDialog() {
    this.setState({dialogOpen: true});
  }
  
  closeDialog() {
    this.setState({dialogOpen: false});
  }
  
  render() {
    return (
      <View>
        <Button
          text="Open Dialog - Default Animation"
          onPress={this.openDefaultAnimationDialog}
        />

        <PopupDialog
          dialogTitle={
            <TouchableOpacity onPress={this.clsoeDialog()} />
              <Text>Close<Text>
            </TouchableOpacity>
          }
          open={this.state.dialogOpen}
        >
          <View>
            <Text>Slide Animation</Text>
          </View>
        </PopupDialog>
      </View>
    );
  }
}

# Example - 2
export default class PopupDialogExample extends Component {
  constructor(props) {
    super(props);

    this.state = {
      dialogOpen: false,
    };

    this.openDialog = this.openDialog.bind(this);
    this.closeDialog = this.closeDialog.bind(this);
  }

  openDialog() {
    this.popupDialog.openDialog();
  }

  closeDialog() {
    this.popupDialog.closeDialog();
  }

  render() {
    return (
      <View>
        <PopupDialog
          ref={(defaultAnimationDialog) => {
            this.popupDialog = popupDialog;
          }}
          dialogTitle={
            <View>
              <TouchableOpacity onPress={this.clsoeDialog()} />
                <Text>Close<Text>
              </TouchableOpacity>
            </View>
          }
        >
          <View>
            <Text>Default Animation</Text>
          </View>
        </PopupDialog>
      </View>
    );
  }
}
```

**Comment by sances15** [comment]
@jacklam718 Thanks alot. That worked just like i needed.

**Comment by XeCtvi** [comment]
Hi @jacklam718 ,

Seems `open={this.state.dialogOpen}   // open is boolean ` doesn't work for now right?

To open the dialog, we have to call `show()` method instead?

Thanks.
