### ISSUE TITLE
Align two dialogbutton side by side.

### ISSUE THREAD

**Issue by BipinAle** [jacklam718/react-native-popup-dialog#142]
I am wondering if two dialog buttons can be aligned side to side.

**Comment by jacklam718** [comment]
@BipinAle like this?

<img src="https://user-images.githubusercontent.com/5494638/49597952-88d8ac00-f9b8-11e8-
8d41-8b5f71843f9b.PNG" width="500" />

**Comment by BipinAle** [comment]
> @BipinAle like this?
> 
> <img alt="" width="400" src="https://user-images.githubusercontent.com/5494638/49598125-f553ab00-f9b8-11e8-8b80-2ad93cca8437.PNG">

yes.

**Comment by jacklam718** [comment]
you can take a look on README https://github.com/jacklam718/react-native-popup-dialog#usage---dialog-action 
or example
