### ISSUE TITLE
Can I set maximum height for the dialog

### ISSUE THREAD

**Issue by naveedshahji** [jacklam718/react-native-popup-dialog#144]

**Comment by jacklam718** [comment]
```javascript
<Dialog
  height={1.0}
/>
```

**Comment by naveedshahji** [comment]
I wan to change the height according to the content. The content is dynamic, the height should be maximum for maximum content and minimum for minimum content. and it is not working for that. another issue I have noticed that If I have contact more than 1300 words then the whole layout is disturbed and If I use scrollview, it is not showing some content at the end.
