### ISSUE TITLE
Android, popupDialog not able to close/setState when component located outside the body

### ISSUE THREAD

**Issue by Jacky9425** [jacklam718/react-native-popup-dialog#145]
Hi Sir, i have this `Dialog `component from the package where i included a QUIT button image and make it `onPress()` to `setState `visible of dialog to false so that the dialog closes. The code works with IOS device but Android phone is not showing any response. 

Then when i include the button into the `popupBody ``View` component, the dialog is closed on pressing the button.

May i know what is the issue here causing the behavior?

**Comment by ShooterArk** [comment]
@Jacky9425 how did you solve it? I am unable to close the dialog now. Everything is fine in the previous version but for this project I used the latest version and its not working properly. The dialog appears fine but its not closing at all. not even when I set dismissOnTouchOutside to true. Its getting really frustrating now. Please advise.

**Comment by jacklam718** [comment]
@ShooterArk Hi, please take a look on [README](https://github.com/jacklam718/react-native-popup-dialog). `dismissOnTouchOutside` is removed since  `v0.16`, you can use `onTouchOutside` handler for example:
```
<Dialog 
  visible={this.state.visible}
  onTouchOutside={() => {
    this.setState({ visible: false })
  }}
>
```

**Comment by ShooterArk** [comment]
@jacklam718 
I have already tested the OnTouchOutside function. But still its not working for me. Here is my code:

`<Dialog visible={this.state.showModal} width={screen.width/1.4} height={screen.width/1.6}  
            dialogTitle={<DialogTitle titleStyle={{backgroundColor: 'transparent', borderBottomColor: 'black', 
            borderBottomWidth: 2, borderWidth: 2,}} 
            titleTextStyle={{ color: 'black', fontSize:20, backgroundColor: 'transparent'}} titleAlign="left" 
            title="Select a template" />}
            dialogStyle={{justifyContent: 'center', alignItems: 'center'}}
            ref={(popupDialog) => { this.popupDialog = popupDialog; }}
            onTouchOutside={() => {
              this.setState({ showModal: false });
            }}
            // dialogAnimation={slideAnimation}
          > 
            <DialogContent>
            <Button style={{width: '100%', justifyContent: 'center', marginBottom: 10}}>
              {/* <Text>Welcome everyone!</Text> */}
              <Icon name="ios-paper" />
              <Text>Simple Note</Text>
            </Button>
            <Button onPress={this._handleButtonClick.bind(this, "patient")} style={{width: '100%', justifyContent: 'center'}}>
              {/* <Text>Welcome everyone!</Text> */}
              <Icon name="ios-medkit" />
              <Text>Patient Note</Text>
            </Button>
            </DialogContent>
          </Dialog>`

Please advise. Thanks
