### ISSUE TITLE
 I have content more than 1300 words then the whole layout is disturbed

### ISSUE THREAD

**Issue by naveedshahji** [jacklam718/react-native-popup-dialog#146]
I wan to change the height according to the content. The content is dynamic, the height should be maximum for maximum content and minimum for minimum content. and it is not working for that. another issue I have noticed that If I have content more than 1300 words then the whole layout is disturbed and If I use scrollview, it is not showing some content at the end.

**Comment by jacklam718** [comment]
```javascript
<Dialog>
  <ScrollView>
    <DialogContent>
      <Text>
        Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
        Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
      </Text>
    </DialogContent>
  </ScrollView>
</Dialog>
```

and you can set height on `Dialog` or `ScrollView` component.

**Comment by naveedshahji** [comment]
thanks it is working fine when I set height , but there is another issue, I want the height dynamic, I want the maximum height for maximum content and less height for less content. for example if I have only one line text then the height should be {0.4} for two line the height should be {0.5} and similarly {0.9} for maximum content. my content is dynamic. the issue is there is no dynamic option for the height. is there any way to solve this issue.

**Comment by jacklam718** [comment]
you can set maxHeight for view:
<Dialog dialogStyle={{maxHeight: '90%'}} />
or 
<ScrollView style={{maxHeight: '90%'}} />

**Comment by naveedshahji** [comment]
okay thanks
