### ISSUE TITLE
Extremely slow to render

### ISSUE THREAD

**Issue by ajonno** [jacklam718/react-native-popup-dialog#15]
I havent figured out why yet, but after adding this component and looking to display it in render() , it takes like 10 seconds or so before it surfaces. If you have encountered this before appreciate if u can let me know why. ill keep looking at this in the mean time when i get a chance.

**Comment by jacklam718** [comment]
@ajonno 
Please give me more info:
What OS and Version are you using?
Have you enabled Debug JS Remotely?
Only the dialog very slow?

**Comment by fmelp** [comment]
Same situation here. Quite an old android tablet, but much heavier things such as mapbox run great on it

**Comment by jacklam718** [comment]
Really want to know the fps for Native and JS thread when you open the Dialog

**Comment by fmelp** [comment]
how do you get that info? happy to run that for you

**Comment by jacklam718** [comment]
You can access the developer menu by shaking your device or by selecting "Shake Gesture" 
https://facebook.github.io/react-native/docs/debugging.html

**Comment by jacklam718** [comment]
Then you can select `Show Perf Monitor`

**Comment by fmelp** [comment]
Both running around 60fps

**Comment by jacklam718** [comment]
Do you using `console.log` or enabled remote debugging?

**Comment by fmelp** [comment]
console.log

**Comment by jacklam718** [comment]
Try remote console.log it may affect performance on RN

**Comment by jacklam718** [comment]
@fmelp Does it work?

**Comment by fmelp** [comment]
Hey, tried everything but was still a little slow for me. Had to use something else cause these tablets i need to use for the job are total whack. Thanks so much!!

**Comment by jacklam718** [comment]
Okay

**Comment by Clowning** [comment]
I have the same issue! When I use JS Debugging it takes a looong seconds to show modal, if I disable it, it appear instantly !

**Comment by punksta** [comment]
animations does not use nativeDriver in this library. I believe it's a the reason of speed bug.

**Comment by jacklam718** [comment]
@Clowning FYI: 
https://github.com/facebook/react-native/issues/5632
https://github.com/facebook/react-native/issues/10559

**Comment by jacklam718** [comment]
I've add `useNativeDriver` and set it to true by default.
you can use latest `v0.13.46`

**Comment by punksta** [comment]
Hi @jacklam718, It's much better with useNativeDriver. Thanks.

**Comment by jacklam718** [comment]
@punksta  thanks for letting me know
