### ISSUE TITLE
using more than one Dialog on a page give me error 

### ISSUE THREAD

**Issue by naveedshahji** [jacklam718/react-native-popup-dialog#154]
Warning: Failed prop type: Prop `children` has type 'any' or 'mixed', but was not provided to `DialogContent`. Pass undefined or any other value.

**Comment by jacklam718** [comment]
It's type warning. `children` is required for `DialogContent` component https://github.com/jacklam718/react-native-popup-dialog/blob/master/src/type.js#L59
