### ISSUE TITLE
Closing the popup

### ISSUE THREAD

**Issue by Norfeldt** [jacklam718/react-native-popup-dialog#16]
I'm using the NativeBase for the UI and trying to implement the missing parts like popups. 

I got it working like the example, but encounted an issue when trying to add a submit button. 

```
<Container>
    <Content>
          <List dataArray={this.state.items}
            renderRow={(item) =>
              <ListItem key={item.key} onPress={() => {
                  this.popupDialog.openDialog();
                }}>
                  <Text>{item.title}</Text>
              </ListItem>
            }
          />

          <PopupDialog
            ref={(popupDialog) => { this.popupDialog = popupDialog; }}
            dialogTitle={<DialogTitle title="Be Awesome!" />}
            actions={[<DialogButton text="Submit" align="center" onPress={this.closeDialog} key="ImSpecial"/>]}
            dialogAnimation = { new SlideAnimation({ slideFrom: 'bottom' }) }
          >
            <View>
              <Text>React Community is Awesome</Text>
            </View>
          </PopupDialog>

        </Content>
</Container>
```

Pressing the Submit button doesn't close the dialog... What am I missing?

**Comment by jacklam718** [comment]
@Norfeldt 
1. Did you defined the `closeDialog` method if so can you post the `closeDialog` method of body here?
2. If you defined the method, did you bind the method on constructor? for example `this.closeDialog = this.closeDialog.bind(this);`

**Comment by Norfeldt** [comment]
@jacklam718 I didn't do step 1. I just dropped the code right in to see if it would work.

**Comment by jacklam718** [comment]
@Norfeldt 
That's why doesn't work because you haven't defined the `closeDialog` method.

Here have example you can check it out: https://github.com/jacklam718/react-native-popup-dialog/blob/master/popupDialogExample/PopupDialogExample.js

**Comment by Norfeldt** [comment]
@jacklam718 thank you very much. 

Awesome project BTW
