### ISSUE TITLE
undefined visible option

### ISSUE THREAD

**Issue by devvlop** [jacklam718/react-native-popup-dialog#164]
export default class ProductsShow extends React.Component{
  state={
    productbox:false,
  };
.......
}

I have created a state for show dialog popup but now I have this warning:
Failed prop type: The prop 'visible' is marked as required in 'PopupDialog'. but its value is 'undefined'.
 
How can I fix that?

**Comment by jacklam718** [comment]
because `visible` is 'undefined' not boolean type
