### ISSUE TITLE
onHardwareBackPress behaviour

### ISSUE THREAD

**Issue by Boubaker93** [jacklam718/react-native-popup-dialog#165]
Hello guys,
I used onHardwareBackPress so that when the user presses the back button the dialog gets dismissed like this : 
`onHardwareBackPress={() => {
                    onDismiss();
                    return true
                }}`
But the problem i'm facing is that after i press the back button the dialog gets dismissed, but the back button does not work properly anymore as long as the dialog component is present.
Am i not using this property properly or is this a bug ?

Thanks.

**Comment by jacklam718** [comment]
Hi @Boubaker93 Thanks for report. This issue has been fixed in `v0.17.3`

**Comment by cani1see** [comment]
@jacklam718  Hi I think this problem is back again(0.18.2)
