### ISSUE TITLE
Handle hardware button Click cannot be closed

### ISSUE THREAD

**Issue by guoquanonly** [jacklam718/react-native-popup-dialog#175]
react native:0.57.7
react-native-popup-dialog: "^0.18.2"

Clicking the back button on android does not respond
 I have set onHardwareBackPress={()=>true}

**Comment by jacklam718** [comment]
You didn't put your logic inside the onHardwareBackPress handler.
You could take a look on the example https://github.com/jacklam718/react-native-popup-dialog/blob/master/popup-dialog-example/App.js#L161-L165

**Comment by antonioreyna** [comment]
hello, i have the same problem
