### ISSUE TITLE
upgrade react-native-root-siblings to 3.2.1

### ISSUE THREAD

**Issue by kamiky** [jacklam718/react-native-popup-dialog#177]
Could you upgrade react-native-root-sibling to the last version (3.2.1).

see https://github.com/magicismight/react-native-root-siblings/issues/43
it would fix this kind of error.

in my case i have a duplicated instance of react-native-root-siblings and react-native-popup-dialog doesnt show up because of it, the last version fixes this issue.

**Comment by star-heng** [comment]
same error
