### ISSUE TITLE
How to open the dialog in specific location on the screen

### ISSUE THREAD

**Issue by Jaafar-abusair** [jacklam718/react-native-popup-dialog#18]
How to open the dialog in specific location on the screen

**Comment by bird512** [comment]
You can use the margin value in the dialogStyle like below:
```
dialogStyle={{marginTop:-300}}
```

**Comment by jacklam718** [comment]
@Jaafar-abusair 
The answer is like @bird512 said. Then I will close this issue.
@bird512 Thank you  for answer the question.
