### ISSUE TITLE
Dialog disappears after state change

### ISSUE THREAD

**Issue by Arman92** [jacklam718/react-native-popup-dialog#19]
Dialog disappears when I make a change in state (in which causes to re-render the page), only the gray modal background stays.

**Comment by Arman92** [comment]
Actually this issue occurs only if I add a dialogAnimation, without animation, it works fine

**Comment by Arman92** [comment]
Also when I have two PopupDialogs (one over the other) and I call closeDialog(), the other dialog will disapper two!
However when I remove`this.props.dialogAnimation.animations` from styles of `<Animated.View>`, it will be fixed, but with no animation of course.

here is a gif of what happens:
![ezgif com-808180a64f](https://cloud.githubusercontent.com/assets/3900575/21482710/e7930ab2-cb8c-11e6-9e13-f26e83aee962.gif)

**Comment by jacklam718** [comment]
@Arman92 
Sorry to reply you so late.
I guess you shared the animation instance to the two dialogs, is it right?
If so, I think you can try to apply Animation instances to each dialog.
For example:
```
import PopupDialog, { DefaultAnimation } from 'react-native-popup-dialog';

<View style={styles.container}>
  <Button
    text="Open Dialog A"
    onPress={() => {
      this.popupDialogA.openDialog();
    }}
  />

  <Button
    text="Open Dialog B"
    onPress={() => {
      this.popupDialogB.openDialog();
    }}
  />
  
  <PopupDialog
    ref={(popupDialogA) => { this.popupDialogA = popupDialog; }}
    dialogAnimation = { new DefaultAnimation() }
  >
    <View>
      <Text>Dialog A</Text>
    </View>
  </PopupDialog>
  
  <PopupDialog
    ref={(popupDialogB) => { this.popupDialogB = popupDialog; }}
    dialogAnimation = { new DefaultAnimation() }
  >
    <View>
      <Text>Dialog B</Text>
    </View>
  </PopupDialog>
</View>
```

**Comment by jacklam718** [comment]
@Arman92 
Did you try? Is it working?

**Comment by Arman92** [comment]
Sorry to for late reply,
I didn't use a shared animation, however I had wrapped the PopupDialog into my own ModalDialog (which is just a wrapper to pass default props to PopupDialog), I removed the wrapper and used PopupDialog directly, but didn't make a different.

The main problem is that changing in state, will disappear the dialog.

**Comment by jacklam718** [comment]
@Arman92 
Can you show me your code?

**Comment by jacklam718** [comment]
@Arman92 
Do you mind show me your code?
I want to investigate what problem is it.

**Comment by Arman92** [comment]
Sorry I was in a trip.

Here is the wrapper class:
`
    const { width, height } = Dimensions.get("window")


    class ModalDialog extends React.Component {
        props: {
            animationSlide: 'top' | 'bottom' | 'right' | 'left';
            title: string;
            style?: any;
            width: number;
            height: number;
            refr: () => mixed;
            animationDuration: number;
            closeOnTouchOutside: boolean
        };

        static defaultProps = {
            animationSlide: 'bottom',
            title: 'Default title',
            animationDuration: 300,
            closeOnTouchOutside: true,
            width: width * 0.75,
            height: 300,
        };

        constructor(props) {
            super(props);
        }


        render() {
            return (

            	<PopupDialog
                    width={this.props.width}
                    height={this.props.height}
                    ref={this.props.refr}
                    dialogAnimation = { new SlideAnimation({ slideFrom: this.props.animationSlide })}
                    dialogTitle={
                        <DialogTitle 
                            title={this.props.title} 
                            titleTextStyle={{color:"#212121"}} 
                            titleStyle={{backgroundColor:"#DEDEDE"}} />
                        }
                    animationDuration={this.props.animationDuration}
                    overlayBackgroundColor={"#616161"}
                    overlayOpacity={0.6}
                    closeOnTouchOutside={this.props.closeOnTouchOutside}
                    {...this.props}
                >

                	{this.props.children}

                </PopupDialog>

                
            );
        }
    }


    var styles = StyleSheet.create({

    });

    module.exports = ModalDialog;
`

This is the first dialog, it was quite big so I didnt include the inner elements.
I open below dialog by calling "this.chartSettingDlg.openDialog()" and close it using "this.chartSettingDlg.closeDialog()".

`      <ModalDialog
         height={height * 0.40}
         width={width * 0.85}
         refr={(chartSettingDlg) => { this.chartSettingDlg = chartSettingDlg; }}
         closeOnTouchOutside={true}
         title={I18n.t("CarDetails.ChartSettingsDlgTitle")}
      >
      .....lots of codes here
      </ModalDialog>`


`And this is the color picking dialog (the second dialog shown in previous gif)

      <ModalDialog
        height={400}
        width={400}
        refr={(colorPickerDlg) => { this.colorPickerDlg = colorPickerDlg; }}
        closeOnTouchOutside={true}
        title={I18n.t("CarDetails.PickAColor")}
      >
        <View style={{flexDirection: 'column', justifyContent: 'center', flex:1}}>

            <ColorPicker
                defaultColor={this.state.fieldColors[this.state.fieldNumToColorPicking]}
                onColorChange={color => this.setState({ selectedTempColor: color })}
                style={{flex: 1, margin: 20}}
            />

            <View style={{flexDirection: 'row', margin:15, justifyContent: 'space-around'}}>
                <IconnedButton style={{paddingHorizontal: 20, paddingVertical:10}}
                    onPress={() => {
                        this.colorPickerDlg.closeDialog();
                    }}
                >
                    <Text>{I18n.t("General.Dismiss")}</Text>
                </IconnedButton>

                <IconnedButton style={{paddingHorizontal: 20, paddingVertical:10}}
                onPress={() => {
                    let { fieldColors } = this.state;
                    fieldColors[this.state.fieldNumToColorPicking] = 
                    fromHsv(this.state.selectedTempColor);

                    this.setState({fieldColors: fieldColors});
                    this.colorPickerDlg.closeDialog();
                }}
                >
                    <Text>{I18n.t("General.Apply")}</Text>
                </IconnedButton>
            </View>
        </View>
      </ModalDialog>
`


In any of above dialogs, if I make a change in state, both of them will disappear.

**Comment by jacklam718** [comment]
@Arman92 
I still don't know why.
I tried on my side, it's working properly.
![react-native-popup-dialog-issue19-2](https://cloud.githubusercontent.com/assets/5494638/21581212/75efe0f8-d062-11e6-8a7e-ab0cb9b4d674.gif)

**Comment by kenma9123** [comment]
@jacklam718 try it on android. You'll see the problem, because I was able to replicate it myself. Disabling animation works like a charm.

**Comment by boliveira** [comment]
Hi,

I was having the same problem and I can confirm disabling animations fix this. I have two popups displayed and when I dismiss the front popup the back would disappear after dismissing the first

**Comment by Dror-Bar** [comment]
I can confirm this behavior.
It's not game breaking, but it is slightly inconvenient.

**Comment by tangtai** [comment]
i had the same issue, after state change the dialog disappears, i really like to use animate for the component, i wish this can be fixed~

**Comment by jacklam718** [comment]
@Arman92 
Keep animation instance and don't share same instance for multiple dialog.
Reference https://github.com/jacklam718/react-native-popup-dialog/issues/28#issuecomment-330815162

**Comment by CorentinDupont** [comment]
Hi everyone i have the same issue but this time i'm not using animations at all ! I can't close the second popup without closing the first one. Any help again on this topic ?

**Comment by jacklam718** [comment]
hmmm... could you show me your code?

**Comment by CorentinDupont** [comment]
**This is my base component for every popup dialog**

`class CustomPopupDialog extends Component {
  constructor() {
    super();
    this.state = {
      inputText: 'ex : soireedeouf',
      inputIsFocus: false,
      marginTopValue: 0,
      marginOffset: 0
    }
    this.replacePopup = this.replacePopup.bind(this);
    this.keyboardDidHide = this.keyboardDidHide.bind(this);
    this.keyboardDidShow = this.keyboardDidShow.bind(this);
    this.setMarginOffset = this.setMarginOffset.bind(this);
  }

  componentDidMount() {
    this.props.onRef(this)
    this.keyboardDidShowListener = Keyboard.addListener('keyboardDidShow', this.keyboardDidShow);
    this.keyboardDidHideListener = Keyboard.addListener('keyboardDidHide', this.keyboardDidHide);
  }
  componentWillUnmount() {
    this.props.onRef(undefined)
    this.keyboardDidShowListener.remove();
    this.keyboardDidHideListener.remove();
  }

  showDialog(){
    this.popupDialog.show();
  }

  hideDialog(){
    this.popupDialog.dismiss();
  }

  keyboardDidShow (e) {
    this.elevatePopup(e)
  }

  keyboardDidHide () {
    this.replacePopup();
  }

  elevatePopup(e){
    this.setState({marginTopValue: - (Dimensions.get('window').height - e.endCoordinates.height - 200) + this.state.marginOffset})
    this.setState({inputIsFocus:true})
  }

  replacePopup(){
    this.setState({inputIsFocus:false})
  }

  // Method call by child element
  setMarginOffset(marginOffset){
    this.setState({marginOffset:marginOffset})
  }

  render() {

    const { width, height, title, buttons:{ positive, negative } } = this.props;
    
    return (
        <PopupDialog
          ref={(popupDialog) => { this.popupDialog = popupDialog; }}
          width={width}
          dialogStyle={styles.dialog}
          height={height}
          containerStyle={ {zIndex:1000000, elevation:100000, marginTop: this.state.inputIsFocus ? this.state.marginTopValue : 0}}
          onDismissed={Keyboard.dismiss}
        >
          
            {/* Dialog Title */}
            <Text style={styles.dialogTitle}>{title}</Text>

            {/* Dialog Content */}
            <View style={styles.dialogContentContainer}>
              {this.props.children}
            </View>

            {/* Dialog Button Container */}
            <View style={styles.dialogButtonContainer}>
              {/* Negative button */}
              <TouchableOpacity onPress={negative.onPress}>
                <Text style={styles.dialogButton}>{negative.label}</Text>
              </TouchableOpacity>
              {/* Positive button */}
              <TouchableOpacity onPress={positive.onPress}>
                <Text style={styles.dialogButton}>{positive.label}</Text>
              </TouchableOpacity>
            </View>
        </PopupDialog>
      
    );
  }
}

export default CustomPopupDialog;`

**this is the first popup shown on the screen**

`class RemeCreatorPopupDialog extends Component {
  constructor() {
    super();
    this.state = {
      popupDialog:null,
      reme:null,
      isForCreate:false,
      remeInfoList:[]
    }
    this.setReme = this.setReme.bind(this)
    this.initReme = this.initReme.bind(this)
    this.addInfoToReme = this.addInfoToReme.bind(this)
    this.showDialog = this.showDialog.bind(this)
    this.hideDialog = this.hideDialog.bind(this)

    this.initReme()
    
  }

  componentDidMount() {
    this.props.onRef(this)
  }
  componentWillUnmount() {
    this.props.onRef(undefined)
  }

  showDialog(){
    this.popupDialog.showDialog();
  }

  hideDialog(){
    this.popupDialog.hideDialog();
  }

  setReme(selectedReme){
    this.setState({reme:selectedReme})
  }

  setIsForCreate(isForCreate){
    this.setState({isForCreate:isForCreate})
  }

  initReme(){
    this.state.reme = {}
    this.state.reme.word="Papillon"
    this.state.reme.content=[
    ]
    this.state.reme.isFake=false

  }

  addInfoToReme(info){
    this.state.remeInfoList.push(info)
  }


  render() {
    
    const { addRemeInfoPopupDialog } = this.props;

    return (

      <CustomPopupDialog
        onRef={(popupDialog) => { this.popupDialog = popupDialog; }}
        width={320}
        height={'90%'}
        title={ this.state.isForCreate ? "Nouveau Reme" : "Modifier mon reme"}
        buttons={{
          positive:{
            label: this.state.isForCreate ? "AJOUTER" : "MODIFIER",
            onPress:() => {this.popupDialog.hideDialog();}
          },
          negative:{
            label:"FERMER",
            onPress:() => {this.popupDialog.hideDialog();}
          }
        }}
      >
        {/* popup dialog custom content */}

       

        {/* Title info list block */}
        <View style={styles.infoListTitleContainer}>
          <Text style={styles.infoListTitle}>Liste de mes informations</Text>
          <TouchableOpacity 
            style={styles.addInfoButton} 
            onPress={ () => {addRemeInfoPopupDialog.showDialog()} }
          >
            {/* Plus icon */}
            <Image
              style={styles.plusIcon}
              source={Images.icon.plusLightWhite}
            />
            <Text style={styles.addInfoButtonText}>Ajouter</Text>
          </TouchableOpacity>
        </View>
      </CustomPopupDialog>
    );
  }
}

export default RemeCreatorPopupDialog;`

**The second popup opened with the first one**

`class AddRemeInfoPopupDialog extends Component {
  constructor() {
    super();
    this.state = {
      addRemeInfoCustomDialog:null,
      labelInputText:"",
      contentInputText:""
    }
    this.showDialog = this.showDialog.bind(this);
    this.hideDialog = this.hideDialog.bind(this);
  }

  componentDidMount() {
    this.props.onRef(this);
  }
  componentWillUnmount() {
    this.props.onRef(undefined);
  }

  showDialog(){
    this.addRemeInfoCustomDialog.showDialog();
  }

  hideDialog(){
    this.addRemeInfoCustomDialog.hideDialog();
  }


  render() {

    const { reme } = this.props;
    
    return (

      
      <CustomPopupDialog
        onRef={(addRemeInfoCustomDialog) => { this.addRemeInfoCustomDialog = addRemeInfoCustomDialog; }}
        width={280}
        height={300}
        title="Ajouter une information"
        buttons={{
          positive:{
            label:"AJOUTER",
            onPress: () => {}
          },
          negative:{
            label:"ANNULER",
            onPress:() => {this.addRemeInfoCustomDialog.hideDialog();}
          }
        }}
      >
      
      {/* popup dialog custom content */}
     
      </CustomPopupDialog>
      
    );
  }
}

export default AddRemeInfoPopupDialog;`

**Comment by CorentinDupont** [comment]
Thank you for your answer. Well your dialogs and your buttons to show them are in the same component/view. My dialogs are declared in parent of my current view, and i pass the reference to use "myDialogRef.show()". I will try to reproduce your example with my mecanic and see if my problem persists.
