### ISSUE TITLE
Modal portal not working

### ISSUE THREAD

**Issue by gax97** [jacklam718/react-native-popup-dialog#254]
I am trying to use ModalProtal. I have it rendered somewhere on the top level. When I call
`ModalPortal.show(
                    <Text>Show this</Text>
                )`
                from some component underneath nothing happens and  I get this warning:
![image](https://user-images.githubusercontent.com/12710366/102936725-f4f7b100-44a8-11eb-882e-8c7dbe5d4000.png)

**Comment by jacklam718** [comment]
@gax97 what version?

**Comment by gax97** [comment]
@jacklam718 0.21.1

**Comment by jacklam718** [comment]
the fix prop-types warning should be fixed in `v0.22.3`. also with some fixes in the latest version, you could try that out.
