### ISSUE TITLE
Suggestion: add props for borderRadius

### ISSUE THREAD

**Issue by jeongmincha** [jacklam718/react-native-popup-dialog#27]
I think someone may want to use rectangle dialog content without any borderRadius or with different borderRadius. However, by using existing codes, we cannot easily set up borderRadius value without modifying codes.

I think that we can add a property for borderRadius and control the borderRadius of dialog content.

I also suggest that documentation about the way passing props of PopupDialog be more made up for developers to use this library more easily.

If you think it's a good idea, I am going to make PR for this issue. :)

**Comment by jacklam718** [comment]
@jeongmincha 
I'm appreciate your pull request. Acctually, you can pass style via the `dialogStyle` prop to change the borderRadius.
For example:
```javascript
<PopupDialog
  ref={(popupDialog) => { this.popupDialog = popupDialog; }}
  dialogAnimation = { new SlideAnimation({ slideFrom: 'bottom' }) }
  dialogStyle={{
    borderRadius: 0,
  }}
>
  <View>
    <Text>Hello</Text>
  </View>
</PopupDialog>
```
