### ISSUE TITLE
setState donesn't work well with Animation

### ISSUE THREAD

**Issue by jeongmincha** [jacklam718/react-native-popup-dialog#28]
In my dialog content, there are buttons to change states. (onPress handlers of the buttons are going to change the state)
When I click the button and change the state, my popup dialog view would be gone!
When I don't use Animation, it works fine.

**Comment by jacklam718** [comment]
@jeongmincha can you show me your code?

**Comment by edwinbosire** [comment]
I think this is related to #19 

When presenting/dismissing the dialog by observing state changes (via Redux or otherwise) only the background loads but the actual popup view is no where to be seen.

**Comment by jacklam718** [comment]
@jeongmincha Thank you to report the issue. I'll investigate it.

**Comment by pengfeiyan** [comment]
I have the same issue.

**Comment by Louis345** [comment]
I also had to disable animations to get the modal render probably. Any update on this?

**Comment by scottplong** [comment]
I also had to disable animations to fix a disappearing popup after a state change (android)

**Comment by readthecodes** [comment]
I have the same issue.

**Comment by cristiangu** [comment]
You just need to keep one SlideAnimation instance.
`constructor(){
    super();
    this.popupAnimation = new SlideAnimation({ slideFrom: "bottom" });
  }`

The use it like this:

` <PopupDialog
        onDismissed={this.onDismissed.bind(this)}
        dialogAnimation={this.popupAnimation}
      >`

**Comment by jorgemarrero** [comment]
@cristiangu that works for me too.
