### ISSUE TITLE
How do I remove the white background when I use modalportal.show ()

### ISSUE THREAD

**Issue by XuanChuYun** [jacklam718/react-native-popup-dialog#297]
ModalPortal.show((
        <Image
            source={require('../../assets/images/loading.gif')}
            style={{width: 50, height: 50}}
        />
))
![2022 04 17_10 15 17](https://user-images.githubusercontent.com/29687766/163697394-9b2d7a14-e37e-46a0-aa06-868fe0bb975f.jpg)

**Comment by StevenRogers** [comment]
modalStyle={{ backgroundColor: colors.transparent }}

**Comment by XuanChuYun** [comment]
> modalStyle={{ backgroundColor:colors.transparent }}

thank you
