### ISSUE TITLE
dismissOnTouchOutside is not work in android

### ISSUE THREAD

**Issue by frankyLHJ** [jacklam718/react-native-popup-dialog#30]
I use the library version is ^0.6.22, When I set dismissOnTouchOutside = false, haveOverlay = true, it does not work properly. Why is this?

**Comment by jacklam718** [comment]
@frankyLHJ 
I found the reason and I'll fix it soon. Will let you know it's fixed.
Thank you for report the issue.

**Comment by jacklam718** [comment]
@frankyLHJ Fixed. Please install `0.7.22` version, if there are any issues please let me know. Thanks!

**Comment by behnamt** [comment]
In version 0.7.22, dismissOnTouchOutside with overlay = true, still doesn't work

**Comment by jacklam718** [comment]
@behnamt can you show me your code?

**Comment by behnamt** [comment]
sorry, the problem was with packager. I just restart it and it got fixed
