### ISSUE TITLE
How to resize when keyboard opens?

### ISSUE THREAD

**Issue by frmdstryr** [jacklam718/react-native-popup-dialog#31]
I have a dialog with a `TextInput`, when the input is focused, the keyboard opens and covers it. Is it possible to resize the dialog when the keyboard opens? 

https://github.com/Andr3wHur5t/react-native-keyboard-spacer did not work (resized the main view, not the modal).

Thanks!

**Comment by jacklam718** [comment]
@frmdstryr I have no plan to integrate with [react-native-keyboard-spacer](https://github.com/Andr3wHur5t/react-native-keyboard-spacer) at the moment. So you could do that by yourself.

**Comment by est7** [comment]
@frmdstryr did u implement it?

**Comment by frmdstryr** [comment]
No. Just changed the positioning of the popup

**Comment by faustoct** [comment]
what worked for me..
something like this

`<Dialog.Container style={{position:'absolute'}}>`

you could positioning it better as you want
