### ISSUE TITLE
Unexpected token in components/Dialog.js

### ISSUE THREAD

**Issue by vault13tech** [jacklam718/react-native-popup-dialog#33]
while I upgrade 0.5.20 -> 0.7.22
it shows the error below at runtime:
`node_modules/react-native-popup-dialog/src/components/Dialog.js: Unexpected token, expected , (16:14)`
seems the problem is at
`import { type DialogType} from ...`

run on: 
react 15.4.2
react-native 0.41.2

any suggestion??

**Comment by joegoodall1** [comment]
Getting the same error ^^^^

**Comment by jacklam718** [comment]
@vault13tech @joegoodall1 I tried but I didn't get the error  🤔

**Comment by joegoodall1** [comment]
Problem seems to have resolved itself. Thanks for replying so quickly.

**Comment by vault13tech** [comment]
interesting...
@jacklam718 I'll try to figure out what happened
@joegoodall1 is there any clue to be notice??

**Comment by jacklam718** [comment]
@vault13tech Thanks a lot

**Comment by joegoodall1** [comment]
This error seems to be back now when trying to build apk for release?

**Comment by joegoodall1** [comment]
Just noticed in the packager that react-native-pop-up-dialog gets missed out?  

`:react-native-linear-gradient:transformNative_libsWithSyncJniLibsForRelease UP-TO-DATE
:react-native-linear-gradient:bundleRelease UP-TO-DATE
:react-native-sound:preBuild UP-TO-DATE
:react-native-sound:preReleaseBuild UP-TO-DATE`

**Comment by jacklam718** [comment]
@vault13tech @joegoodall1 Can you try install this version `0.7.23` ? This version might be can solve  the issue.

**Comment by vault13tech** [comment]
at first, I tried to upgrade to 0.7.23 directly, it show some error message at runtime,
then I just uninstall and reinstall again, it works just fine! (how strange).

thank you @jacklam718 , excellent works :+1:

**Comment by jacklam718** [comment]
@vault13tech Nice.

**Comment by vault13tech** [comment]
oh!! we got problems.
when I tried to build a app release, the error shown:
`TransformError: \Projects\ProjectA\node_modules\react-native-popup-dialog\index.js: Unknown plugin "flow-react-proptypes" specified in "\\Projects\\ProjectA\\node_modules\\react-native-popup-dialog\\.babelrc" at 0, attempted to resolve relative to "\\Projects\\
ProjectA\\node_modules\\react-native-popup-dialog"`

**Comment by jacklam718** [comment]
@vault13tech So sorry. I will fix it.

**Comment by vault13tech** [comment]
@jacklam718 
I change .babelrc from
`"plugins": ["babel-plugin-flow-react-proptypes"]`
to
`"env": {
	"development": {
		"plugins": ["babel-plugin-flow-react-proptypes"]
	}
}`

it will only work on development

**Comment by jacklam718** [comment]
@vault13tech Can you try install this version `0.7.24` thanks.

**Comment by vault13tech** [comment]
@jacklam718 I accidentally install the version: 0.7.26 :smile: 
and it seems works fine both on development & release build.
thanks again :smile:

**Comment by jacklam718** [comment]
@vault13tech Nice. So sorry about that 😅
