### ISSUE TITLE
Module does not exist (react-native-popup-dialog/dist/Type.js)

### ISSUE THREAD

**Issue by pedroordep** [jacklam718/react-native-popup-dialog#36]
The version 0.7.26 give this error when running react-native start:

`UnableToResolveError: Unable to resolve module prop-types from [home]/node_modules/react-native-popup-dialog/dist/Type.js: Module does not exist in the module map or in these directories:
  [home]/node_modules`

Rollbacking to version 0.7.22 by running `npm install --save react-native-popup-dialog@0.7.22` solves the issue, but forces us to use the outdated version.

**Comment by loopArray** [comment]
hi, I have the same problem and found the solutions:
 [ React.PropTypes is deprecated as of React v15.5. Please use the prop-types  library instead.](https://facebook.github.io/react/docs/typechecking-with-proptypes.html)

**Comment by jacklam718** [comment]
@pedroordep @loopArray Very sorry. I will fix it soon.

**Comment by jacklam718** [comment]
@loopArray I solved `React.PropTypes is deprecated` issue. Please install the version `0.7.27`

**Comment by jacklam718** [comment]
@pedroordep Can you try install this version `0.7.27` ?

**Comment by pedroordep** [comment]
Works like a charm. Thanks for the quick fix @jacklam718
