### ISSUE TITLE
Popup hidden behind Card Container

### ISSUE THREAD

**Issue by jacksonywl** [jacklam718/react-native-popup-dialog#39]
Apparently the popup is hidden behind react-native-elements' {card} container. Tried using elevation and some other methods but can't get it working yet. Any idea?

**Comment by rawanabbas** [comment]
I have the same exact problem did you solve it?

**Comment by jlamarr22** [comment]
Try setting the `zIndex` on the card to 0. I used the react-native-elements cards, but ended up having issues with them and decided to just roll my own. You could also try setting the zIndex of the dialog itself to something very high.
