### ISSUE TITLE
Exporting the Popup Dialog as module

### ISSUE THREAD

**Issue by msciotti** [jacklam718/react-native-popup-dialog#40]
I'm attempting to re-use my code for the popup dialog as a navigation menu throughout my app. The button appears properly when used in other pages, but the popup does not show.

Code for popup dialog:

```
import React, { Component } from 'react';
import { View, Text, Button } from 'react-native';
import PopupDialog, { DialogTitle } from 'react-native-popup-dialog';

class MenuPopup extends Component {
    render(){
        return(
            <View>
                <Button title="Navigation" onPress={() => this.popUpDialog.show()} />
                <PopupDialog
                    dialogTitle={<DialogTitle title="Navigation" />}
                    ref={ (popupDialog) => this.popUpDialog = popupDialog } 
                >
                    <View>
                        <Text>This is my menu</Text>
                    </View>
                </PopupDialog>
            </View>
        )
    }
}

module.exports = MenuPopup;
```

Use in another page:

```
import MenuPopup from './MenuPopup';

render(){
    return (      
        <Image source={require('./images/pixelsky.jpg')} style={styles.backgroundImage}>
          <ListView
            dataSource={this.state.dataSource}
            renderRow={this.renderRow.bind(this)}
          />
          <MenuPopup />          
        </Image>      
    );
}
```

The button's `onPress` function fires properly; if I change it to log something to console, I see the message. But it seems the `.show()` method is not displaying the popup properly. Am I misunderstand the use of this package perhaps?

**Comment by jacklam718** [comment]
@msciotti Thank you for reporting the issue. Btw this is an interesting use case.

**Comment by msciotti** [comment]
@jacklam718 No problem; appreciate the prompt response. I'm fairly new to react-native, so what I'm doing very well may not be best practice. I was searching for themable in-app navigation solutions, and liked your package, so I tried it out.

I could always recreate the menu in each page if necessary; just figured I'd try to save some code if I could.

**Comment by msciotti** [comment]
Hey @jacklam718, was wondering if you had any progress with this? If not, I can refactor. Thanks!

**Comment by jacklam718** [comment]
@msciotti Not sure what do you mean by `Exporting the Popup Dialog as module` PopupDialog already export as module.

**Comment by msciotti** [comment]
@jacklam718 My terminology might be wrong; I'm very new to react-native and JavaScript languages in general. What I'm saying is creating a separate class of my own design `MenuPopup` that includes the `Button` and `PopUpDialog` to be used throughout my app, so I don't have to copy and paste the code in my original post everywhere I want to use my Navigation Popup.

**Comment by jacklam718** [comment]
@msciotti 
Understood, this is quite specific feature and use case. On my point of view as a general component should not implement a specific feature for specific use case. So I will not implement that at this moment.

**Comment by msciotti** [comment]
No problem at all. Going to continue to play around with your library, as I really like the way it works. Thank you for making it, and I hope it can serve my purpose :)
