### ISSUE TITLE
Overlay layer hidden by the NavBar

### ISSUE THREAD

**Issue by loregr** [jacklam718/react-native-popup-dialog#42]
If used with https://github.com/aksonov/react-native-router-flux the overlay layer of the dialog is hidden by the navbar. Is there any way to draw it on top of the navbar?

Thanks

**Comment by poojanshah2005** [comment]
+1

**Comment by jacklam718** [comment]
@loregr @poojanshah2005 
### This is the reason:
This is happening because the modal is defined as a child of the navigator. React native doesn't support zindex but yields that type of behavior based on the rendering order.

### Solution: 
###### Put `Dialog` and `Navigator` on same layer
```javascript
<View style={{ flex: 1 }}>
  <Navigator
    initialRoute={{
      name: 'index',
      title: 'Popup Dialog',
    }}
    ref={(navigator) => {
      this.navigator = navigator;
    }}
    navigationBar={navigationBar}
    renderScene={this.renderScene}
    configureScene={this.configureScene}
    style={styles.navigator}
  />

  <PopupDialog
    ref={(defaultAnimationDialog) => {
      this.defaultAnimationDialog = defaultAnimationDialog;
    }}
    dialogTitle={<DialogTitle title="Popup Dialog - Default Animation" />}
  >
    <View style={styles.dialogContentView}>
      <Text>Default Animation</Text>
    </View>
  </PopupDialog>
</View>
```

I updated example app you can check it out [Example App](https://github.com/jacklam718/react-native-popup-dialog/blob/master/popup-dialog-example/PopupDialogExample.js)
[Reference (Stackoverflow)](https://stackoverflow.com/questions/37741689/backdrop-does-not-cover-the-the-navigation-bar-for-react-native-modalbox)

**Comment by SelfnessAid** [comment]
So we can't use this package with react-native-router-flex?

**Comment by jacklam718** [comment]
@SelfnessAid What do you mean? the solution doesn't work?

**Comment by SelfnessAid** [comment]
@jacklam718 
Thanks for quick reply
My problem is follow.
Now I am using react-native-router-flex to navigate.
I'd like this package on one scene.
But popup dialog doesn't show up.
![image](https://user-images.githubusercontent.com/20356023/29420803-c613cce4-837b-11e7-97c4-02ac41d6063e.png)

**Comment by jacklam718** [comment]
@loregr Can you me your code?

**Comment by SelfnessAid** [comment]
yes

**Comment by jacklam718** [comment]
@loregr 
1. As I mentioned we just put it on same layer with the navigation bar
For example:
```javascript
<Router>
  <Scene key="root">
    <Scene key="login" component={Login} title="Login"/>
    <Scene key="register" component={Register} title="Register"/>
    <Scene key="home" component={Home}/>
    <PopupDialog
      ref={popupDialog => {this.popupDialog = popupDialog}}
    >
      <View>
        <Text>
          Hello
        </Text>
      </View>
    </PopupDialog>
  </Scene>
</Router>
```
2. But popup dialog doesn't show up.
I didn't see where you call the `show` method

**Comment by SelfnessAid** [comment]
chatbot/index.js line331

**Comment by SelfnessAid** [comment]
I put wrong logic to use this package?
I am new on RN

**Comment by jacklam718** [comment]
@SelfnessAid Did you read this? https://stackoverflow.com/questions/37741689/backdrop-does-not-cover-the-the-navigation-bar-for-react-native-modalbox

**Comment by SelfnessAid** [comment]
So I can't use this package on chatbot/index.js, right?

**Comment by jacklam718** [comment]
I'm not sure. But, there explained the reason with a solution

**Comment by SelfnessAid** [comment]
okay, got it
Thanks for your help so far

**Comment by jacklam718** [comment]
@SelfnessAid And the solution is works for me. But, I use React Native's navigator API

**Comment by XeCtvi** [comment]
Hi @jacklam718 ,

If I put the dialog in the same layer of the parent component or navigation component.
How can I call the show method or the dismiss method in the child component?

What I mean is like:

```
<View style={ mainPosition }>
    <PopupDialog
        ref={ (popUpDialog) => this.popUpDialogForSearch = popUpDialog }
        // open={ this.state.dialogVisible }
        onDismissed={() => {
            this.setState({
                dialogVisible: false
            });
        }}
        width={0.7}
        height={0.7}
        containerStyle={{
            // TODO: dynamic height
            marginTop: -50,
        }}
        dialogTitle={
        <DialogTitle
            title="入库单搜索"
            haveTitleBar={false}
            popUpIns={this.popUpDialogForSearch}
        />
    }>
            { <SearchForm /> }  // <---- To pass the instance `this.popUpDialogForSearch` here?
    </PopupDialog>
    ...
</View> 
```

Thanks.

**Comment by zek** [comment]
> @SelfnessAid
> 
> 1. As I mentioned we should put `PopupDialog` on same layer with the navigation bar
>    For example:
> 
> ```js
> <Router>
>   <Scene key="root">
>     <Scene key="login" component={Login} title="Login"/>
>     <Scene key="register" component={Register} title="Register"/>
>     <Scene key="home" component={Home}/>
>     <PopupDialog
>       ref={popupDialog => {this.popupDialog = popupDialog}}
>     >
>       <View>
>         <Text>
>           Hello
>         </Text>
>       </View>
>     </PopupDialog>
>   </Scene>
> </Router>
> ```
> 
> 1. But popup dialog doesn't show up.
>    I didn't see where you call the `show` method

I also use as you show but this doesn't sound good for me. What I want is showing the popup dialog in another screen (For ex: src/pages/user.js) like

```
Popup.show('user', modalProps);
```

So I want to pass props. Right now I have a rootStore but that doesn't sound good.

In router-flux it is possible to show a modal as ```Actions.modal(props)```  Is it possible to provide a similar API? 

Providing a sample router-flux + popup-dialog together would be super cool for me and other users.
