### ISSUE TITLE
BackAndroid is deprecated since react-native 0.44

### ISSUE THREAD

**Issue by wenbinf** [jacklam718/react-native-popup-dialog#43]
Use [BackHandler](https://facebook.github.io/react-native/releases/next/docs/backhandler.html) instead: https://github.com/jacklam718/react-native-popup-dialog/blob/master/src/components/Dialog.js

**Comment by jacklam718** [comment]
@wenbinf 
Thanks for the reminder.
But I still have no idea how to handle backward compatibility for `react-native < 0.44`
So any suggestions for how to handle backward compatibility are welcomed.
Thanks
