### ISSUE TITLE
Popup is not closing itself

### ISSUE THREAD

**Issue by DavitVosk** [jacklam718/react-native-popup-dialog#44]
I see this package doesn't have any features, which will allow the popup to disapperar after, for instance, 3 sec. If there is, then please point me. Thanks in advance

**Comment by mmatheusmmiguel** [comment]
I also want to know ...

**Comment by jacklam718** [comment]
@DavitVosk 
Uou can do something like this:

<View style={styles.container}>
  <Button
    text="Close"
    onPress={() => {
      this.popupDialog.dismiss();
    }}
  />
  <PopupDialog
    ref={(popupDialog) => { this.popupDialog = popupDialog; }}
  >
    <View>
      <Text>Hello</Text>
    </View>
  </PopupDialog>
</View>
