### ISSUE TITLE
Status bar not hidden

### ISSUE THREAD

**Issue by chucky6413** [jacklam718/react-native-popup-dialog#57]
The status bar and the layer of the popupDialog are the same, but the overlay does not cover the status bar for multiple attempts. How can I hide it?

![abc](https://user-images.githubusercontent.com/13410316/29002092-ad00082a-7ad5-11e7-9738-5dfa22ca09a0.png)

**Comment by jacklam718** [comment]
Duplicated with [#42](https://github.com/jacklam718/react-native-popup-dialog/issues/42)

**Comment by chucky6413** [comment]
@jacklam718 
Is it possible to use Android?

**Comment by jacklam718** [comment]
@chucky6413 I though you are talk about hide the **NavigationBar**
For the **StatusBar** you can do something this `<StatusBar hidden={true} />`
Please check the docs https://facebook.github.io/react-native/docs/statusbar.html
you can implement the logic by you self

**Comment by chucky6413** [comment]
@jacklam718
Thank you very many times for your answers. 
However, is there any way to overlay the StatusBar with an overlay without Navigator?
I tried many different ways, but I did not succeed.

**Comment by jacklam718** [comment]
@chucky6413 I don't know how to overlay the StatusBar. I know how to hide the StatusBar only.

**Comment by jacklam718** [comment]
@chucky6413 I don't know. But seems it's not my component's issue.
