### ISSUE TITLE
Open dialog on startup?

### ISSUE THREAD

**Issue by shlomi84** [jacklam718/react-native-popup-dialog#58]
How can I have this dialog open up automatically when a component is loaded. I tried so many different combinations in my render:

  1. {() => this.popupDialog.show()} this just doesn't do anything in my app
  2. {this.popupDialog.show()} this gives me a warning: undefined is not an object this.popupDialog.show
3. {this.popupDialog.show}

none of these work, but if I make a touchableOpacity and do:
    onPress={() => {
      this.popupDialog.show();
    }}

the dialog pops up. So how can I start it up when my screen is loaded?

**Comment by jacklam718** [comment]
@shlomi84 
Please check the docs https://facebook.github.io/react/docs/react-component.html
Basic example is something like this
```javascript
class App extends Component {
  componentDidMount() {
    this.dialog.show();
  }

  render() {
    return (
      <View>
        <PopupDialog 
          ref={dialog => {this.dialog = dialog}}
        >
        </PopupDialog>
      <View>
    )
  }
}
```
