### ISSUE TITLE
Cannot read property 'openDialog' of undefined

### ISSUE THREAD

**Issue by Rolando-Barbella** [jacklam718/react-native-popup-dialog#6]
Hey, thank's for this, I'm trying to use the popup in my project for android, I'm getting this error when I press the button 

`Cannot read property 'openDialog' of undefined`

The code is exactly as the example you have here https://github.com/jacklam718/react-native-popup-dialog/blob/master/popupDialogExample/PopupDialogExample.js

"react": "15.3.2",
 "react-native": "0.33.0",
 "react-native-popup-dialog": "0.0.6",

Any reason why is  saying that?

**Comment by jacklam718** [comment]
@Rolando-Barbella 
Are you running the example app directly or copy the example code from `PopupDialogExample. js` & paste into your project?

If you are copying the example code from `PopupDialogExample. js` & paste into your project, can you paste the whole file of source code in here or send to my email jacklam718@gmail.com ? I think it would be easier to debug.

Except the Cannot read property `openDialog` of undefined error, have you see any other errors in your debug console?

Thank you for reporting this issue 👍

**Comment by Rolando-Barbella** [comment]
Hey, thanks for the quick answer and sorry for my late reply (hectic week), I got it working, I forgot to add the styles from the example (don't know what's the relationship there with the error I was getting), but now, it is showing a tiny pop-up window, in the readme looks much bigger, is that way is supposed to be? bellow the code
```
import React, { Component } from 'react';
import PopupDialog from 'react-native-popup-dialog';
import {
  AppRegistry,
  StyleSheet,
  Text,
  TouchableHighlight, 
  Dimensions,
  View
} from 'react-native';

const { width: WIDTH, height: HEIGHT } = Dimensions.get('window');

class myApp extends Component {
  constructor(props) {
    super(props);

    this.state = {
      dialogOpen: false,
    };

    this.openDialog = this.openDialog.bind(this);
  }

  openDialog() {
    this.popupDialog.openDialog();
  }
  render() {
    return (
       <View style={styles.container}>
        <TouchableHighlight style={styles.button} onPress={this.openDialog}>
          <Text style={styles.buttonText}>Open Dialog</Text>
        </TouchableHighlight>
        <PopupDialog
          ref={(popupDialog) => {
            this.popupDialog = popupDialog;
          }}
          title="Popup Dialog"
        >
          <View>
            <Text>Hello</Text>
          </View>
        </PopupDialog>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    // backgroundColor: '#000',
  },
  button: {
    // flexDirection:'column',
    width: WIDTH * 0.4,
    height: HEIGHT * 0.08,
    borderRadius: 50,
    // borderColor: 'black',
    borderWidth: 0,
    backgroundColor: '#009688',
    justifyContent: 'space-around',

  },
  buttonText: {
    alignSelf: 'center',
    fontSize: 15,
    color: 'rgba(255,255,255,0.9)',
    fontWeight: '100',
  },
});

AppRegistry.registerComponent('myApp', () => myApp);

```
```
{
  "name": "myApp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start"
  },
  "dependencies": {
    "react": "15.3.2",
    "react-native": "0.34.0",
    "react-native-popup-dialog": "0.0.6"
  }
}

```

**Comment by jacklam718** [comment]
@Rolando-Barbella 
1. Did you try the component on exponent? If so, is it also shows a tiny pop-up window on your device?

2. If you post screenshots here would be better.

**Comment by Rolando-Barbella** [comment]
Is looking fine now, sometimes you have to restart everything with react native in order to get things working properly, (I'm newbie on mobile development), thanks a lot for your answers

**Comment by jacklam718** [comment]
Nice!

**Comment by jacklam718** [comment]
Then I'll close this issue.
