### ISSUE TITLE
TransformError

### ISSUE THREAD

**Issue by hongsa** [jacklam718/react-native-popup-dialog#60]
I use
{"react": "16.0.0-alpha.12",
"react-native": "0.45.1",
"react-native-popup-dialog": "^0.9.33"}

Unknown plugin "flow-react-proptypes" error occoured!

How can i fix this?

**Comment by jacklam718** [comment]
@hongsa Fix in version `0.9.34`

**Comment by bm-software** [comment]
This problem is still present in version `0.14.50`. Can you fix?

**Comment by jacklam718** [comment]
@bm-software Probably I moved `flow-react-proptypes` to devDependencies recently. I moved it back to dependencies. please update to latest version.

**Comment by jacklam718** [comment]
@bm-software Does it works?

**Comment by bm-software** [comment]
@jacklam718 I've just tried and now it works fine! Thank you!
