### ISSUE TITLE
Touchables & header is not overlaying

### ISSUE THREAD

**Issue by RameshkrishnanV** [jacklam718/react-native-popup-dialog#66]
Hi, 

    i'm using react navigation & redux in my react native app, react-native-popup-dialog is not overlaying the touchable button & navigation bar

**Comment by jacklam718** [comment]
@RameshkrishnanV 
Seems duplicated this issue [42](https://github.com/jacklam718/react-native-popup-dialog/issues/42)

**Comment by RameshkrishnanV** [comment]
No...I'm using react navigation in that how i can add the popup in that top of the layer?
