### ISSUE TITLE
How do I disable navbar back button from react-native-router-flux

### ISSUE THREAD

**Issue by princenaman** [jacklam718/react-native-popup-dialog#67]
I have a scene where in I have a back button. But I want it to be disabled when the Dialog is shown.
Can that be done?
I already have these:
```js
      dismissOnTouchOutside={false}
      dismissOnHardwareBackPress={false}
```
<img width="374" alt="screen shot 2017-09-09 at 11 51 21 pm" src="https://user-images.githubusercontent.com/6601879/30242743-e997fd8e-95b9-11e7-9c0f-e1f2f91e74b2.png">

**Comment by jacklam718** [comment]
@princenaman I think you need to study the react-native-router-flux API
