### ISSUE TITLE
How can I add styles for content container

### ISSUE THREAD

**Issue by jungleyu** [jacklam718/react-native-popup-dialog#70]
I create an instance of the dialog, but set the content dynamically, once the dialog height is fixed, there will be blank area in the dialog if content doesn't occupy the full of dialog.

**Comment by jacklam718** [comment]
@jungleyu You can pass style via `dialogStyle` prop

for example:
```javascript
<PopupDialog
  dialogStyle={{ }} // style
>
</PopupDialog>
```
