### ISSUE TITLE
No full screen

### ISSUE THREAD

**Issue by leogittest** [jacklam718/react-native-popup-dialog#76]
![image](https://user-images.githubusercontent.com/21074918/31709123-a5ec6286-b423-11e7-8b8b-7600e1624ab0.png)

**Comment by jacklam718** [comment]
@leogittest What navigation library are you using?
This [#42 Overlay layer hidden by the NavBar](https://github.com/jacklam718/react-native-popup-dialog/issues/42) might be helpful for you
