### ISSUE TITLE
Android: Back button listener race condition

### ISSUE THREAD

**Issue by cpetzel** [jacklam718/react-native-popup-dialog#79]
If you navigate from a screen that has a DialogComponent, to another screen that has a DialogComponent, there is a bit of a race condition with the way this lib adds back press listeners. 

'componentDidMount' will be called twice before the first one has the change to remove his listeners in componentWillUnmount. Then when the last one is unmounted, the BackHandler doesn't know which one to remove. 

Steps to repro. 

Using StackNavigator, display a screen that has a Dialog in its view hierarchy. Then navigate to another screen that also has a Dialog. I this screen, show the dialog, and then navigate away from this screen while the dialog is open (without programmatically dismissing it). You'll see that whenever you press back on Android, the dialog that was open and visible before is swallowing all of the back press events. 

With the PR below, this will allow the second dialog to unregister the correct back press handler.

**Comment by jacklam718** [comment]
@cpetzel Thank you for reporting this problem and your PR.
