### ISSUE TITLE
A question in the basic usage

### ISSUE THREAD

**Issue by chen4393** [jacklam718/react-native-popup-dialog#81]
In your usage, you note that:
``
<View style={styles.container}>
  <Button
    text="Show Dialog"
    onPress={() => {
      this.popupDialog.show();
    }}
  />
</View>
``
Is the "text" prop in Button should be "title"? I think your Button has conflict with the built-in Button.
Also, this onPress cannot pop up the dialog

**Comment by jacklam718** [comment]
@chen4393 It's just example.

**Comment by jacklam718** [comment]
@chen4393 However I updated README. Thanks for your opinion!
