### ISSUE TITLE
Change content of Dialog 

### ISSUE THREAD

**Issue by MinhNQ90** [jacklam718/react-native-popup-dialog#83]
Hi guys,
I'm developing real-time app that when first person do a event then the 2nd will get data of the first one.
And in the 2nd person screen will appear Dialog that show person 1 data. But now when i'm doing i found that the Dialog always show the default coz mobile render the Dialog content before i call function open it.
So how can i change the content or set the Dialog render content when i call the function popupDialog.show() ?

**Comment by jacklam718** [comment]
You means you need have some ways to update the content. Right?

**Comment by MinhNQ90** [comment]
yes that exactly what i need i just want to pull data to Dialog whenever the event occur

**Comment by jacklam718** [comment]
@MinhNQ90 
It's not related to this component, it's about React. But, Anyway I can explain a bit about the question.
Basically, you don't have to call any method to update/re-render the view, React will do it. When the date (might be via component's `state` or `props`) is updated then React will re-render the view.
you could do some experiment, for example:

```javascript
import React, { Component } from 'react';
import { View, Text } from 'react-native';
import PopupDialog from 'react-native-popup-dialog';

class App extends Component {
  state = {
    currentTime: new Date(),
  }

  componentDidMount() {
    this.refreshTime();
  }
  
  refreshTime() {
    setTimeout(() => {
      this.setState({ currentTime: new Date() });
    }, 1000);
  }
  
  render() {
    return (
      <View>  
        <PopupDialog>
          <View>
            <Text>{this.state.currentTime}</Text>
          </View>
        </PopupDialog> 
      </View>
    );
  }
}
```

**Comment by MinhNQ90** [comment]
So sorry for bother you again.
This is my function inside componentDidMount()

`this.socket.on('SERVER-SENT-CUSTOMER-TO-STAFF', function(data){
		if(data.code == 'SCTD-001'){
			json = data.data;
			this.customerInfor();
			dialog.show();
		}
	});`

and this is 
`customerInfor() {
    setInterval(() => {
      this.setState({ data: json});
    }, 1000);
  }`

or last time i try to pass argument to customerInfor() but it always  notice that
undefined is not a function ( evaluation this.customerInfor() ).
i think `customerInfor();` is wrong but i don't know how to fix it.
Pls help me. Thank you so much.

**Comment by jacklam718** [comment]
use `() => {}` instead instead `function` it is because.

**Comment by MinhNQ90** [comment]
Sorry i don't get what you mean.
Could you please modify the source code which i paste above ?

**Comment by jacklam718** [comment]
You need to pass your `class` scope into function.
Anyway.. the following code should work.

```javascript
this.socket.on('SERVER-SENT-CUSTOMER-TO-STAFF', (data) => {
  if (data.code == 'SCTD-001') { 
    this.customerInfor(data); dialog.show();
  } 
});

AND 
customerInfor = (data) => {
  setInterval(() => {
    this.setState({ data: data }); 
  }, 1000); 
}}
```

**Comment by MinhNQ90** [comment]
It works thank you so much <3 you're my savior <3
