### ISSUE TITLE
Type.js could not resolve as a file nor folder

### ISSUE THREAD

**Issue by MinhNQ90** [jacklam718/react-native-popup-dialog#85]
After import i got that trouble
![image](https://user-images.githubusercontent.com/33272530/33266316-b1634da2-d3a7-11e7-928e-c173d52a297e.png)
I try to re-install few times but it doesn't work.
How can i solve it ?

**Comment by jacklam718** [comment]
@MinhNQ90 Fixed in `v0.10.43` waiting for tests and build. I'll let you know when it's done.
Thanks for reporting this issue.

**Comment by jacklam718** [comment]
@MinhNQ90 Finished. You can install `0.10.43` now.
