### ISSUE TITLE
Using a string as a width or height raises a type error

### ISSUE THREAD

**Issue by samuelb2** [jacklam718/react-native-popup-dialog#86]
If a percentage string is used as a width or height, an error is raised stating that the width/height needs to be a number contrary to the docs and the actual behavior.

**Comment by jacklam718** [comment]
@samuelb2 Why you pass string type as a width & height?

**Comment by samuelb2** [comment]
@jacklam718 It was my understanding that you must use a string to set the value to a percentage i.e.
```
<PopupDialog
        width="90%"
        height={250}>
{/* Body Here */}
</PopupDialog>
```

If there is a better way to represent percentages, I'd love to know.

**Comment by jacklam718** [comment]
@samuelb2 Sorry for my bad document. the percentage format should be `0.9` rather than `90%`

**Comment by jacklam718** [comment]
I will update the docs

**Comment by samuelb2** [comment]
Just read through Dialog.js and saw that it was handled that way in dialogSize().

That said, using a string value does actually work (it doesn't go into either if statement and is just passed to react native).

To my knowledge, using strings is the only way to enter a percentage using standard react styles so it may be worth considering adding percentage strings as a supported feature.
