### ISSUE TITLE
It doesn't hide button behind!

### ISSUE THREAD

**Issue by thiennhank9** [jacklam718/react-native-popup-dialog#88]
```
 return (
            <View style={styles.container}>
                <Button
                    title='Show Popup List Episodes'
                    onPress={() => this.popupDialog.show()}
                />
                <PopupDialog
                    width={200}
                    dialogTitle={<DialogTitle title="Danh sách các tập" />}
                    ref={(popupDialog) => { this.popupDialog = popupDialog }}
                    dialogAnimation={slideAnimation}>
                    {/* --- Component popup show --- */}
                    <View>
                        <Text> Hello </Text>
                    </View>
                </PopupDialog>
            </View>
        );
```

Here is my code, the problem is when I click button to show dialog, it doesn't hide the button. How to hide behind scene?
![1](https://user-images.githubusercontent.com/18640233/33464839-0d550d72-d677-11e7-977f-e841436439d0.JPG)

**Comment by jacklam718** [comment]
@thiennhank9 Not sure why. You can try to set `zIndex` for dialog container  via `containerStyle` prop

**Comment by jolancornevin** [comment]
I had the same problem and adding a `zIndex` to `containerStyle` worked indeed.

**Comment by nghialt** [comment]
I met the same issue, it's solved by setting zIndex for both container and the popup dialog.

**Comment by VeroGA** [comment]
zIndex is not working for android, any other suggestion?

**Comment by Chetanyg** [comment]
Facing the same issue here, Any solutions?

**Comment by Chetanyg** [comment]
Found one solutions, It is working for me 
`<PopupDialog containerStyle={{ zIndex: 10, elevation: 10 }}  ref={(popupDialog) => { this.popupDialog = popupDialog; }}>
                    <CustomView />
                </PopupDialog>`

**Comment by Bonobomagno** [comment]
Elevation on android is like zIndex, but also as borderShadow. So if the button have elevation, you need to add elevation an all. Without elevation, using zIndex is fine on android too.

Btw, the expo example app need a fix of this type
