### ISSUE TITLE
How to position absolute.

### ISSUE THREAD

**Issue by princenaman** [jacklam718/react-native-popup-dialog#89]
Is it possible to align the popup to the bottom of the screen?

Reference screens:
What I want:
<img width="278" alt="screen shot 2017-12-04 at 1 51 53 pm" src="https://user-images.githubusercontent.com/6601879/33542798-8428a0f0-d8fa-11e7-835a-0034e55d1aa8.png">

What I have:
<img width="382" alt="screen shot 2017-12-04 at 1 53 15 pm" src="https://user-images.githubusercontent.com/6601879/33542808-8a005248-d8fa-11e7-8193-599c056a2fa0.png">

Currently, I have set the width equal to screen width and height is 60% of screen height.
I just need a way to push it down 😞 

Thanks!

**Comment by jacklam718** [comment]
@princenaman You can change dialog's style via `dialogStyle` prop
For example:
```
<PopupDialog 
  dialogStyle={{ bottom: 0 }}
/>
```

**Comment by princenaman** [comment]
Thank you so much!!!

**Comment by jacklam718** [comment]
@princenaman Sorry, should be via `containerStyle` prop
```
<PopupDialog 
  containerStyle={{ justifyContent: 'flex-end'
/>
```

<img src=https://user-images.githubusercontent.com/5494638/33555891-004e2c76-d93d-11e7-8212-4b63c6a04518.PNG width=300 />

**Comment by princenaman** [comment]
This worked:
```dialogStyle={{ position: 'absolute', bottom: 0 }}```

**Comment by rickcha** [comment]
This worked for me well.
```
containerStyle={{ height: '100%' }}
dialogStyle={{ position: 'absolute', bottom: 10 }}
```

**Comment by Cassianokunsch** [comment]
Post the code please

**Comment by princenaman** [comment]
> 
> 
> Post the code please

Entire code?

**Comment by pixelize** [comment]
```jsx
const dialog = StyleSheet.create({
  container: {
    justifyContent: 'flex-end',
  },
  dialog: {
    backgroundColor: '#fff',
    height: '90%',
  },
})
<Dialog
        dialogAnimation={new SlideAnimation()}
        containerStyle={dialog.container}
        dialogStyle={dialog.dialog}
        width={1}
        visible={openModal}
        onTouchOutside={() => setOpenModal(false)}
      >
        <Text>y0</Text>
      </Dialog>
```

**Comment by jeanpitx** [comment]
Post the code dialog and style please

**Comment by pixelize** [comment]
@jeanpitx my code above is working
