### ISSUE TITLE
onShown activate with high delay

### ISSUE THREAD

**Issue by anhmiuhv** [jacklam718/react-native-popup-dialog#91]
onShown only activates after 2 seconds after the dialog is shown. Change `animationDuration` to 10 , activate onShown earlier. The default `animationDuration` is "150" right?

**Comment by jacklam718** [comment]
@anhmiuhv Yes, default is `150`

**Comment by jacklam718** [comment]
1. How do you measure the time?
2. Did you use `console.log` statement? or enabled remote debug?

**Comment by anhmiuhv** [comment]
I run it on my iphone and the delay is quite high

**Comment by jacklam718** [comment]
What if call onShow, onDismiss method immediately when show, dismiss method is called? Is it make more sense?

**Comment by anhmiuhv** [comment]
I think that is good too

**Comment by jacklam718** [comment]
@anhmiuhv Mmmm... that's so weird. Anyway, I've updated this library now it will callback for show, dismiss method, so the callback function will be called immediately. NOTE, If you use callback approach, I think you need to remove onShown, onDismissed prop. Thanks your report!
