### ISSUE TITLE
DialogComponent not show overlay on toolbar 

### ISSUE THREAD

**Issue by vichay** [jacklam718/react-native-popup-dialog#92]
` <DialogComponent
                    haveOverlay={true}
                    width={250}
                    ref={(popupDialog) => { this.popupDialog = popupDialog; }}>
                    <View>
                        <TouchableEffect onPress={() => this.popupDialog.dismiss(() => { })}>
                            <Text>Hello</Text>
                        </TouchableEffect>
                    </View>
</DialogComponent>`

![screenshot_20180123-111633](https://user-images.githubusercontent.com/24197505/35258110-ebf75634-002f-11e8-8495-0b3600ae5d70.png)

**Comment by jacklam718** [comment]
@vichay Seems duplicated with [#42](https://github.com/jacklam718/react-native-popup-dialog/issues/42) you can check it out it might be helpful.

**Comment by vichay** [comment]
Ok thank sir, i'll use DialogManager instead.
