### ISSUE TITLE
Can the popup-dialog auto fit the height of its content instead of having a fixed size?

### ISSUE THREAD

**Issue by a1onexiang2** [jacklam718/react-native-popup-dialog#94]
I have several PopupDialogs in a page, each PopupDialog has to be set a fixed height to avoid applying the default 300 height. I'm worried about the appearance in different devices.

I read the source code, tried a lot such as setState, setNativeProps, onLayout, etc. but nothing works.

So, is there a way to make the PopupDialog auto fit the height of its content? Many thanks.

**Comment by jacklam718** [comment]
@a1onexiang2 I think you can try to pass `null` via `width` & `height` the props.

For example:
```
<PopupDialog 
  width={null}
  height={null}
>
  {...}
</PopupDialog>
```

**Comment by a1onexiang2** [comment]
@jacklam718 I just tried and it truly works. Thanks! You saved my life.

**Comment by jacklam718** [comment]
@a1onexiang2 when I have time I will update the document as well. Thanks!

**Comment by egemon** [comment]
@jacklam718 why can't auto we the default value for both?

**Comment by mrnagydavid** [comment]
For me, right now, height={null} makes the popup appear with 0 height.
