### ISSUE TITLE
Clicking outside of the popup boundaries

### ISSUE THREAD

**Issue by Dror-Bar** [jacklam718/react-native-popup-dialog#98]
Hey there,
In Android, you can dismiss the popup by clicking outside of the popup box.
Is there any way I can disable this behaviour, or alternatively, handle this action somehow?

**Comment by jacklam718** [comment]
I recommend you read the document before ask question 🙄

**Comment by Dror-Bar** [comment]
Haha, I have read it a few times in the past. Of course I read right through it. My apologize jacklam!

**Comment by jacklam718** [comment]
@Dror-Bar  Thanks 😉
