### ISSUE TITLE
Dynamic height

### ISSUE THREAD

**Issue by arronhunt** [jacklam718/react-native-popup-dialog#99]
I am wanting to use this popup for content that is dynamic. I'm curious why I would need to explicitly define a height, or user the default `300`, and not have it respond dynamically with a `maxHeight`

**Comment by jacklam718** [comment]
Hi @arronhunt FYI [Can the popup-dialog auto fit the height of its content instead of having a fixed size?](https://github.com/jacklam718/react-native-popup-dialog/issues/94)

**Comment by arronhunt** [comment]
Thanks @jacklam718, unsure why this isn’t default behavior...
